### ISSUE TITLE
Testing command line start of agent on Windows

### ISSUE THREAD

**Issue by eirbjo** [kantega/notsoserial#20]
Easiest way would be to run WithoutAgentIT with the following cli argument added:

-javaagent:target/notsoserial-1.0-SNAPSHOT.jar

and watch the attack fail because deserialization is rejected.

**Comment by anderius** [comment]
Done. Output was a failed test:

```
java.lang.UnsupportedOperationException: Deserialization not allowed for class org.apache.commons.collections4.functors.InvokerTransformer

    at org.kantega.notsoserial.DefaultNotSoSerial.preventDeserialization(DefaultNotSoSerial.java:189)
    at org.kantega.notsoserial.DefaultNotSoSerial.onBeforeResolveClass(DefaultNotSoSerial.java:183)
    at org.kantega.notsoserial.ObjectInputStreamClassVisitor.onBeforeResolveClass(ObjectInputStreamClassVisitor.java:48)
```

This was what you expected, right?

**Comment by eirbjo** [comment]
Yes :-)
