### ISSUE TITLE
Deserialization not allowed for class jdk.nashorn.internal.ir.FunctionNode

### ISSUE THREAD

**Issue by ghost** [kantega/notsoserial#29]
I am trying to run [Babel Standalone](https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.4.4/babel.js) with Nashorn and get the following error:

```
java.lang.UnsupportedOperationException: Deserialization not allowed for class jdk.nashorn.internal.ir.FunctionNode (on Thu Feb 25 17:27:35 CET 2016)
    at org.kantega.notsoserial.DefaultNotSoSerial.preventDeserialization(DefaultNotSoSerial.java:256)
    at org.kantega.notsoserial.DefaultNotSoSerial.onBeforeResolveClass(DefaultNotSoSerial.java:248)
    at org.kantega.notsoserial.ObjectInputStreamClassVisitor.onBeforeResolveClass(ObjectInputStreamClassVisitor.java:48)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
```

Java code:

```
InputStream stream = getClass().getResourceAsStream("babel-6.4.4.js");
String script = IOUtils.toString(stream);
SimpleBindings bindings = new SimpleBindings();

ScriptEngine engine = new ScriptEngineManager().getEngineByMimeType("text/javascript");
engine.eval(script, bindings);
```

**Edit:** Sorry, should have read the documentation first. Had to whitelist "jdk.nashorn.internal." and "int".

**Comment by joannajasnowska** [comment]
Hi,
I have similar problem. Could you please provide more details of solution? Where can I whitelist "jdk.nashorn.internal"?

**Comment by ghost** [comment]
@joannajasnowska https://github.com/kantega/notsoserial#whitelisting-mode

**Comment by joannajasnowska** [comment]
Thanks, it was helpful; :)
